name: learn-github-actions
on:
  push:
    branches:
      - main
jobs:
  install-package:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: yarn --version
      - run: yarn
      - run: yarn test
      - run: yarn build
      - run: pm2 start nest-ci-cd.api
